-- InBody body composition logs
-- Paste into Supabase SQL editor (project zbcxuffgmjuqarapfdwb) OR run `supabase db push` if you set up migrations.

create table if not exists public.inbody_logs (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references auth.users(id) on delete cascade,
  measured_at     timestamptz not null,
  source          text not null default 'scan' check (source in ('scan','manual','api')),

  -- Core metrics (imperial)
  weight_lb                  numeric(6,2),
  body_fat_pct               numeric(5,2),
  skeletal_muscle_mass_lb    numeric(6,2),
  body_fat_mass_lb           numeric(6,2),
  lean_body_mass_lb          numeric(6,2),
  total_body_water_lb        numeric(6,2),
  protein_lb                 numeric(6,2),
  minerals_lb                numeric(6,2),
  bmi                        numeric(5,2),
  inbody_score               int,
  visceral_fat_level         numeric(4,1),
  bmr_kcal                   int,
  waist_hip_ratio            numeric(4,2),

  -- Segmental lean mass (lb)
  lean_mass_right_arm_lb     numeric(5,2),
  lean_mass_left_arm_lb      numeric(5,2),
  lean_mass_trunk_lb         numeric(5,2),
  lean_mass_right_leg_lb     numeric(5,2),
  lean_mass_left_leg_lb      numeric(5,2),

  -- Segmental body fat (lb)
  fat_mass_right_arm_lb      numeric(5,2),
  fat_mass_left_arm_lb       numeric(5,2),
  fat_mass_trunk_lb          numeric(5,2),
  fat_mass_right_leg_lb      numeric(5,2),
  fat_mass_left_leg_lb       numeric(5,2),

  raw_json        jsonb,
  image_url       text,
  notes           text,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint inbody_logs_user_measured_unique unique (user_id, measured_at)
);

create index if not exists inbody_logs_user_measured_idx
  on public.inbody_logs (user_id, measured_at desc);

-- RLS
alter table public.inbody_logs enable row level security;

drop policy if exists "inbody_logs_select_own" on public.inbody_logs;
create policy "inbody_logs_select_own"
  on public.inbody_logs for select
  using (auth.uid() = user_id);

drop policy if exists "inbody_logs_insert_own" on public.inbody_logs;
create policy "inbody_logs_insert_own"
  on public.inbody_logs for insert
  with check (auth.uid() = user_id);

drop policy if exists "inbody_logs_update_own" on public.inbody_logs;
create policy "inbody_logs_update_own"
  on public.inbody_logs for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "inbody_logs_delete_own" on public.inbody_logs;
create policy "inbody_logs_delete_own"
  on public.inbody_logs for delete
  using (auth.uid() = user_id);
