create table if not exists public.body_measurements (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users(id) on delete cascade,
  date           date not null,
  weight_lb      numeric,
  waist_in       numeric,
  chest_in       numeric,
  hips_in        numeric,
  left_arm_in    numeric,
  right_arm_in   numeric,
  left_thigh_in  numeric,
  right_thigh_in numeric,
  neck_in        numeric,
  body_fat_pct   numeric,
  notes          text,
  source         text not null default 'manual',
  created_at     timestamptz not null default now(),
  constraint body_measurements_user_date_unique unique (user_id, date)
);

alter table public.body_measurements enable row level security;

create policy "Users can manage own body measurements"
  on public.body_measurements
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
