-- Workout tracking: persist current day in a split + name-based exercise history
-- Paste into Supabase SQL editor (project zbcxuffgmjuqarapfdwb) OR run `supabase db push` if you set up migrations.

-- ─── custom_workouts (bring under version control) ─────────────────────────
create table if not exists public.custom_workouts (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  days        jsonb not null default '[]'::jsonb,
  created_at  timestamptz not null default now()
);

alter table public.custom_workouts
  add column if not exists current_day_index int not null default 0;

alter table public.custom_workouts
  add column if not exists updated_at timestamptz not null default now();

alter table public.custom_workouts enable row level security;

drop policy if exists "custom_workouts_select_own" on public.custom_workouts;
create policy "custom_workouts_select_own"
  on public.custom_workouts for select
  using (auth.uid() = user_id);

drop policy if exists "custom_workouts_insert_own" on public.custom_workouts;
create policy "custom_workouts_insert_own"
  on public.custom_workouts for insert
  with check (auth.uid() = user_id);

drop policy if exists "custom_workouts_update_own" on public.custom_workouts;
create policy "custom_workouts_update_own"
  on public.custom_workouts for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "custom_workouts_delete_own" on public.custom_workouts;
create policy "custom_workouts_delete_own"
  on public.custom_workouts for delete
  using (auth.uid() = user_id);

-- ─── workout_logs (bring under version control) ─────────────────────────────
create table if not exists public.workout_logs (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  date          date not null,
  day_index     int not null,
  exercise_id   text not null,
  done          boolean not null default false,
  sets          jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),

  constraint workout_logs_user_date_day_ex_unique
    unique (user_id, date, day_index, exercise_id)
);

alter table public.workout_logs
  add column if not exists exercise_name text;

create index if not exists workout_logs_user_exercise_date_idx
  on public.workout_logs (user_id, exercise_name, date desc);

alter table public.workout_logs enable row level security;

drop policy if exists "workout_logs_select_own" on public.workout_logs;
create policy "workout_logs_select_own"
  on public.workout_logs for select
  using (auth.uid() = user_id);

drop policy if exists "workout_logs_insert_own" on public.workout_logs;
create policy "workout_logs_insert_own"
  on public.workout_logs for insert
  with check (auth.uid() = user_id);

drop policy if exists "workout_logs_update_own" on public.workout_logs;
create policy "workout_logs_update_own"
  on public.workout_logs for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "workout_logs_delete_own" on public.workout_logs;
create policy "workout_logs_delete_own"
  on public.workout_logs for delete
  using (auth.uid() = user_id);
