-- Workout sessions: one row per user per date, giving the calendar/day-picker
-- a cheap "which days have a workout + what was it called" index.
-- Set-level data continues to live in workout_logs (unchanged).

create table if not exists public.workout_sessions (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  date          date not null,
  name          text not null,
  source        text not null default 'custom',
  source_id     text,
  day_index     int not null default 0,
  total_volume  numeric,
  total_sets    int,
  duration_min  int,
  is_complete   boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint workout_sessions_user_date_unique unique (user_id, date)
);

create index if not exists workout_sessions_user_date_idx
  on public.workout_sessions (user_id, date desc);

alter table public.workout_sessions enable row level security;

drop policy if exists "workout_sessions_select_own" on public.workout_sessions;
create policy "workout_sessions_select_own"
  on public.workout_sessions for select
  using (auth.uid() = user_id);

drop policy if exists "workout_sessions_insert_own" on public.workout_sessions;
create policy "workout_sessions_insert_own"
  on public.workout_sessions for insert
  with check (auth.uid() = user_id);

drop policy if exists "workout_sessions_update_own" on public.workout_sessions;
create policy "workout_sessions_update_own"
  on public.workout_sessions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "workout_sessions_delete_own" on public.workout_sessions;
create policy "workout_sessions_delete_own"
  on public.workout_sessions for delete
  using (auth.uid() = user_id);
