-- Progressive overload: normalized per-set tracking
-- workout_exercises: one row per exercise per session
-- workout_sets: one row per completed set
-- These coexist with the existing workout_logs JSONB table; new writes go to both.

-- ─── workout_exercises ────────────────────────────────────────────────────────
create table if not exists public.workout_exercises (
  id            bigint generated by default as identity primary key,
  session_id    bigint not null references public.workout_sessions(id) on delete cascade,
  exercise_name text not null,
  "order"       int not null default 0,
  created_at    timestamptz not null default now(),

  constraint workout_exercises_session_name_unique
    unique (session_id, exercise_name)
);

create index if not exists workout_exercises_session_idx
  on public.workout_exercises (session_id);

create index if not exists workout_exercises_name_idx
  on public.workout_exercises (exercise_name);

alter table public.workout_exercises enable row level security;

drop policy if exists "workout_exercises_select_own" on public.workout_exercises;
create policy "workout_exercises_select_own"
  on public.workout_exercises for select
  using (
    exists (
      select 1 from public.workout_sessions ws
      where ws.id = workout_exercises.session_id
        and ws.user_id = auth.uid()
    )
  );

drop policy if exists "workout_exercises_insert_own" on public.workout_exercises;
create policy "workout_exercises_insert_own"
  on public.workout_exercises for insert
  with check (
    exists (
      select 1 from public.workout_sessions ws
      where ws.id = workout_exercises.session_id
        and ws.user_id = auth.uid()
    )
  );

drop policy if exists "workout_exercises_update_own" on public.workout_exercises;
create policy "workout_exercises_update_own"
  on public.workout_exercises for update
  using (
    exists (
      select 1 from public.workout_sessions ws
      where ws.id = workout_exercises.session_id
        and ws.user_id = auth.uid()
    )
  );

drop policy if exists "workout_exercises_delete_own" on public.workout_exercises;
create policy "workout_exercises_delete_own"
  on public.workout_exercises for delete
  using (
    exists (
      select 1 from public.workout_sessions ws
      where ws.id = workout_exercises.session_id
        and ws.user_id = auth.uid()
    )
  );

-- ─── workout_sets ─────────────────────────────────────────────────────────────
create table if not exists public.workout_sets (
  id            bigint generated by default as identity primary key,
  exercise_id   bigint not null references public.workout_exercises(id) on delete cascade,
  set_number    int not null,
  weight_kg     numeric,
  reps          int,
  completed_at  timestamptz not null default now(),

  constraint workout_sets_exercise_set_unique
    unique (exercise_id, set_number)
);

create index if not exists workout_sets_exercise_idx
  on public.workout_sets (exercise_id);

-- Index for progressive overload lookups: find all sets for an exercise name
-- across sessions, joined through workout_exercises -> workout_sessions (user filter via RLS)
create index if not exists workout_exercises_name_created_idx
  on public.workout_exercises (exercise_name, created_at desc);

alter table public.workout_sets enable row level security;

drop policy if exists "workout_sets_select_own" on public.workout_sets;
create policy "workout_sets_select_own"
  on public.workout_sets for select
  using (
    exists (
      select 1 from public.workout_exercises we
      join public.workout_sessions ws on ws.id = we.session_id
      where we.id = workout_sets.exercise_id
        and ws.user_id = auth.uid()
    )
  );

drop policy if exists "workout_sets_insert_own" on public.workout_sets;
create policy "workout_sets_insert_own"
  on public.workout_sets for insert
  with check (
    exists (
      select 1 from public.workout_exercises we
      join public.workout_sessions ws on ws.id = we.session_id
      where we.id = workout_sets.exercise_id
        and ws.user_id = auth.uid()
    )
  );

drop policy if exists "workout_sets_update_own" on public.workout_sets;
create policy "workout_sets_update_own"
  on public.workout_sets for update
  using (
    exists (
      select 1 from public.workout_exercises we
      join public.workout_sessions ws on ws.id = we.session_id
      where we.id = workout_sets.exercise_id
        and ws.user_id = auth.uid()
    )
  );

drop policy if exists "workout_sets_delete_own" on public.workout_sets;
create policy "workout_sets_delete_own"
  on public.workout_sets for delete
  using (
    exists (
      select 1 from public.workout_exercises we
      join public.workout_sessions ws on ws.id = we.session_id
      where we.id = workout_sets.exercise_id
        and ws.user_id = auth.uid()
    )
  );
